name: Test & Build

on:
  push:
    branches: [ master, devops ]
  pull_request:
    branches: [ master, devops ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [3.1.301]
        os: [macOS-latest, ubuntu-latest, windows-latest]
        tests-paths: [./BruteShark/PcapAnalyzerTest, ./BruteShark/PcapProcessorTest]
        include:
          - os: macOS-latest
            projects-paths: [./BruteShark/BruteSharkCli]
            test-flag: [--no-build]
            build-flag: []
          - os: ubuntu-latest
            projects-paths: [./BruteShark/BruteSharkCli]
            test-flag: [--no-build]
            build-flag: []
          - os: windows-latest
            projects-paths: [./BruteShark]
            test-flag: []
            build-flag: [--no-restore]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:  ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{ matrix.projects-paths }}

    - name: Test
      run: dotnet test --verbosity normal ${{ matrix.test-flag }}
      working-directory: ${{ matrix.tests-paths }}

    - name: Build
      run: dotnet build --configuration Release ${{ matrix.build-flag }}
      working-directory: ${{ matrix.projects-paths }}  
