name: Test & Build

on:
  push:
    branches: [ master, devops ]
  pull_request:
    branches: [ master, devops ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [3.1.301]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:  ${{ matrix.dotnet-version }}
    
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./BruteShark
    
    - name: Test
      run: dotnet test --verbosity normal
      working-directory: ./BruteShark/PcapAnalyzerTest

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./BruteShark
